// File generated by Antigravity - manual construction
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you are using the manual configuration for Android.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you are using the manual configuration for Android.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you are using the manual configuration for Android.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you are using the manual configuration for Android.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvxkKWZ0UgFndTxCJd51fhrnGcvpiVQnc',
    appId: '1:854976838323:android:31da6f098a92997ab54ec6',
    messagingSenderId: '854976838323',
    projectId: 'revenuecat-anahtar',
    storageBucket: 'revenuecat-anahtar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAsAZQb96VTDfDxQAW7112l6vU_6RKXQ',
    appId: '1:854976838323:ios:40b2b9e3d0941bf0b54ec6',
    messagingSenderId: '854976838323',
    projectId: 'revenuecat-anahtar',
    storageBucket: 'revenuecat-anahtar.firebasestorage.app',
    iosBundleId: 'com.botlab.calculator',
  );
}
